### ISSUE TITLE
Script end tag bracket has source.js scope

### ISSUE THREAD

**Issue by aeschli** [textmate/html.tmbundle#65]
From https://github.com/Microsoft/vscode/issues/25790#issuecomment-299671064:

The `source.js` scope on `<` causes colorizing issues:

![screen shot 2017-05-06 at 6 59 20 pm](https://cloud.githubusercontent.com/assets/835148/25776514/3400f52c-328e-11e7-865a-2016693b4435.png)

![screen shot 2017-05-06 at 6 59 31 pm](https://cloud.githubusercontent.com/assets/835148/25776516/3739d948-328e-11e7-8be8-985c91259415.png)

**Comment by infininight** [comment]
This is intentional, if not exactly correct, choice. Since in TextMate the default scope is determined by the character to the right of the caret scoping the `<` of the closing tag as `source.js` better indicates the current scope of the caret.

Which coloring would 'win' would be a VSCode scope ranking question, would think that punctuation should win being later in the tree and thus of a higher specificity.

cc @smlombardi

**Comment by aeschli** [comment]
Fair enough. Makes sense to me. Thanks for the explanation, @infininight
