### ISSUE TITLE
Closing script tag not using font ligatures like other closing tags

### ISSUE THREAD

**Issue by smlombardi** [textmate/html.tmbundle#77]
When you have a script block or src, the closing `</script>` fonts with ligatures such as [Fira Code](https://github.com/tonsky/FiraCode) do not apply the ligature to the `</` as it does with all other tags.

### all other tags
<img width="131" alt="screen shot 2017-10-13 at 1 00 03 pm" src="https://user-images.githubusercontent.com/835148/31557366-73974b54-b016-11e7-9eb0-eb406430c741.png">

### script tag

<img width="291" alt="screen shot 2017-10-13 at 12 55 30 pm" src="https://user-images.githubusercontent.com/835148/31557386-7bfb9854-b016-11e7-8a05-22ecfe5bfcc7.png">

**Comment by infininight** [comment]
Doesn't appear that your in TextMate so I don't know how you can inspect the carets scope, but if you inspect the scope in neither case do we currently specific that a tag is closing. I can't think of any time that a font should care anyway.

The only thing that I can think of is that the `<` in the script closing tag is given an extra scope so that could be interfering? I would consider that a bug though, I don't think scopes should really affect the font rendering.

**Comment by infininight** [comment]
Closing due to this not relating to the grammar but rather likely a editor issue.
