### ISSUE TITLE
Capitalized tag names showing up weirdly

### ISSUE THREAD

**Issue by Rich-Harris** [textmate/html.tmbundle#91]
Hi — apologies if I'm posting this in the wrong place, I came via https://github.com/github/linguist#theres-a-problem-with-the-syntax-highlighting-of-a-file.

Until recently, `html` code blocks would render like this:

<img width="655" alt="screen shot 2018-08-02 at 6 27 17 pm" src="https://user-images.githubusercontent.com/1162160/43614577-093f0384-9682-11e8-8f0c-a86eaedd776f.png">

Suddenly, capitalized tags are rendering like this instead:

<img width="651" alt="screen shot 2018-08-02 at 6 27 03 pm" src="https://user-images.githubusercontent.com/1162160/43614598-18d3c168-9682-11e8-9531-27991b4b5faf.png">

(These screenshots are from [this file](https://github.com/sveltejs/svelte-virtual-list/blob/master/README.md).)

Any ideas what might have caused this change? Thanks!

**Comment by TehShrike** [comment]
Well huh.  It's not actually the capitalization, it looks like, it's element names that aren't in the official list: https://gist.github.com/TehShrike/51972bb52e993b84e414f0cd05a01f72

**Comment by infininight** [comment]
So the grammar is now compliant with HTML 5, custom tags are supported but only those that contain one or more `-` characters. So anything that is not a valid HTML tag and does not have a `-` will be marked as invalid.

But this isn't your issue, from the `{}` portions I see that this is some sort of template language. This is not something supported by the HTML grammar directly but is rather something we handle in other grammars which inherit rules from the HTML grammar.

Now if you were asking for an editor (ie: TextMate/Atom/etc) you could make a custom grammar for the template language or one may exist already. But since you are talking about on Github it would need to be one of the languages they recognize and support. (They do grammars for the top X used grammars on Github, etc.) So you can look at their recognized grammar list to see if it is and what you can do to have it be recognized if so.

Going to close this since it's not an issue with the grammar, but feel free to ask more questions in this thread.
